function [fitresult, gof] = createFit1(depth, porosity)
%CREATEFIT1(DEPTH,POROSITY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : depth
%      Y Output: porosity
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Nov-2019 10:34:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( depth, porosity );

% Set up fittype and options.
ft = fittype( '0.65-b+b*exp(-x/c)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.546881519204984 0.957506835434298];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'porosity vs. depth', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'depth', 'Interpreter', 'none' );
ylabel( 'porosity', 'Interpreter', 'none' );
grid on


